# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'almost_semicircle2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from pyqtgraph import PlotWidget

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString, MultiLineString



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 480, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 380, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 540, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.center_x_input = QtWidgets.QLineEdit(self.centralwidget)
        self.center_x_input.setGeometry(QtCore.QRect(230, 40, 113, 22))
        self.center_x_input.setObjectName("center_x_input")
        self.center_y_input = QtWidgets.QLineEdit(self.centralwidget)
        self.center_y_input.setGeometry(QtCore.QRect(230, 90, 113, 22))
        self.center_y_input.setObjectName("center_y_input")
        self.D_input = QtWidgets.QLineEdit(self.centralwidget)
        self.D_input.setGeometry(QtCore.QRect(230, 150, 113, 22))
        self.D_input.setObjectName("D_input")
        self.H_input = QtWidgets.QLineEdit(self.centralwidget)
        self.H_input.setGeometry(QtCore.QRect(230, 210, 113, 22))
        self.H_input.setObjectName("H_input")
        self.h1_input = QtWidgets.QLineEdit(self.centralwidget)
        self.h1_input.setGeometry(QtCore.QRect(230, 270, 113, 22))
        self.h1_input.setObjectName("h1_input")
        self.h2_input = QtWidgets.QLineEdit(self.centralwidget)
        self.h2_input.setGeometry(QtCore.QRect(230, 330, 113, 22))
        self.h2_input.setObjectName("h2_input")
        self.noc_input = QtWidgets.QLineEdit(self.centralwidget)
        self.noc_input.setGeometry(QtCore.QRect(230, 400, 113, 22))
        self.noc_input.setObjectName("noc_input")
        self.nr_input = QtWidgets.QLineEdit(self.centralwidget)
        self.nr_input.setGeometry(QtCore.QRect(230, 490, 113, 22))
        self.nr_input.setObjectName("nr_input")
        self.nlo_input = QtWidgets.QLineEdit(self.centralwidget)
        self.nlo_input.setGeometry(QtCore.QRect(230, 550, 113, 22))
        self.nlo_input.setObjectName("nlo_input")
        self.nli_input = QtWidgets.QLineEdit(self.centralwidget)
        self.nli_input.setGeometry(QtCore.QRect(230, 610, 113, 22))
        self.nli_input.setObjectName("nli_input")
        self.get_points_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_points_button.setGeometry(QtCore.QRect(100, 710, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.get_points_button.setFont(font)
        self.get_points_button.setObjectName("get_points_button")

        ###
        self.get_points_button.clicked.connect(self.almost_semi_circle)
        ###

        
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(980, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1180, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1480, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.outer_curve_output = QtWidgets.QListWidget(self.centralwidget)
        self.outer_curve_output.setGeometry(QtCore.QRect(930, 60, 201, 711))
        self.outer_curve_output.setObjectName("outer_curve_output")
        self.inner_curve_output = QtWidgets.QListWidget(self.centralwidget)
        self.inner_curve_output.setGeometry(QtCore.QRect(1190, 60, 211, 711))
        self.inner_curve_output.setObjectName("inner_curve_output")
        self.outer_line_output = QtWidgets.QListWidget(self.centralwidget)
        self.outer_line_output.setGeometry(QtCore.QRect(1440, 60, 211, 711))
        self.outer_line_output.setObjectName("outer_line_output")
        self.inner_line_output = QtWidgets.QListWidget(self.centralwidget)
        self.inner_line_output.setGeometry(QtCore.QRect(1690, 60, 191, 711))
        self.inner_line_output.setObjectName("inner_line_output")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1720, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(410, 60, 460, 460))
        self.graphicsView.setObjectName("graphicsView")
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(100, 820, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refresh_button.setFont(font)
        self.refresh_button.setObjectName("refresh_button")

        
        ###
        self.refresh_button.clicked.connect(self.refresh_all)
        ###


        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(410, 610, 461, 291))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("useful_image.png"))
        self.label_15.setObjectName("label_15")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(100, 930, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")

        ###
        self.save_button.clicked.connect(self.save_as_excel)
        ###


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Get Points"))
        self.label_2.setText(_translate("MainWindow", "Y center"))
        self.label_3.setText(_translate("MainWindow", "Diameter D"))
        self.label.setText(_translate("MainWindow", "X center"))
        self.label_4.setText(_translate("MainWindow", "H"))
        self.label_5.setText(_translate("MainWindow", "h1"))
        self.label_6.setText(_translate("MainWindow", "h2"))
        self.label_8.setText(_translate("MainWindow", "# inner curve"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p># outer curve</p><p><span style=\" font-size:10pt; color:#ff0000;\">*Only Odd Number</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "# outer line"))
        self.label_10.setText(_translate("MainWindow", "# inner line"))
        self.get_points_button.setText(_translate("MainWindow", "Get Points"))
        self.label_11.setText(_translate("MainWindow", "Outer Curve"))
        self.label_12.setText(_translate("MainWindow", "Inner Reinforcement Curve"))
        self.label_13.setText(_translate("MainWindow", "Outer Line"))
        self.label_14.setText(_translate("MainWindow", "Inner line"))
        self.refresh_button.setText(_translate("MainWindow", "Refresh"))
        self.save_button.setText(_translate("MainWindow", "Save"))



    def almost_semi_circle(self):
        
    
        center_x = float(self.center_x_input.text())
        center_y = float(self.center_y_input.text())
        D = float(self.D_input.text())
        H = float(self.H_input.text())
        h1 = float(self.h1_input.text())
        h2 = float(self.h2_input.text())
        nc = int(self.noc_input.text())
        nr = int(self.nr_input.text())
        nlo = int(self.nlo_input.text())
        nli = int(self.nli_input.text())
    
        def curve_line_part(center_x, center_y, radius, start_a, end_a, n):
            thetas = np.radians(np.linspace(start_a,end_a, n))
            x = center_x + radius * np.cos(thetas)
            y = center_y + radius * np.sin(thetas)
            curve_part = LineString(np.column_stack([x,y]))
            start_px = radius * float(np.cos(np.radians(start_a)))
            start_py = radius * float(np.sin(np.radians(start_a)))
            end_px = radius * float(np.cos(np.radians(end_a)))
            end_py = radius * float(np.sin(np.radians(end_a)))
            under_line = LineString([(start_px, start_py),(end_px, end_py)])
        
            return curve_part.coords.xy, under_line.coords.xy, curve_part, under_line
    
        radius1 = D/2
        radius2 = radius1 - h1
    
        if H > radius1:
            start_a1 = -np.degrees(np.arcsin((H-radius1)/radius1))
            end_a1 = 180 + np.degrees(np.arcsin((H-radius1)/radius1))
        
        else:
            start_a1 = np.degrees(np.arcsin((radius1 - H)/radius1))
            end_a1 = 180 - np.degrees(np.arcsin((radius1 - H)/radius1))
        
        if (H-h2) > radius1:
            start_a2 = -np.degrees(np.arcsin((H-radius1-h2)/radius2))
            end_a2 = 180 + np.degrees(np.arcsin((H-radius1-h2)/radius2))
    
        else:
            start_a2 = np.degrees(np.arcsin((radius1 - H + h2)/radius2))
            end_a2 = 180 - np.degrees(np.arcsin((radius1 - H + h2)/radius2))
        
        curve1points, l1, curve1, line1 = curve_line_part(center_x, center_y, radius1, start_a1, end_a1, nc)
        curve2points, l2, curve2, line2 = curve_line_part(center_x, center_y, radius2, start_a2, end_a2, nr)
    
        x_c1, y_c1 = curve1points
        x_c2, y_c2 = curve2points
    
        x_L1 = np.linspace(l1[0][0], l1[0][1], nlo)
        
        y_L1 = np.linspace(l1[1][0], l1[1][1], nlo)
        
    
        x_L2 = np.linspace(l2[0][0], l2[0][1], nli+2)
        x_L2 = x_L2[1:-1]
        y_L2 = np.linspace(l2[1][0], l2[1][1], nli+2)
        y_L2 = y_L2[1:-1]
    
        df_oc = {"X_Outer_Curve":x_c1, "Y_Outer_Curve":y_c1}
        df_ic = {"X_Reinforcement_Curve":x_c2, "Y_Reinforcement_Curve":y_c2}
        df_ol = {"X_Outer_Line":x_L1, "Y_Outer_Line":y_L1 }
        df_il = {"X_Reinforcement_Line":x_L2, "Y_Reinforcement_Line":y_L2}
    
        self.df_OC = pd.DataFrame(df_oc)
        self.df_IC = pd.DataFrame(df_ic)
        self.df_OL = pd.DataFrame(df_ol)
        self.df_IL = pd.DataFrame(df_il)
    
        
        for i, p in enumerate(zip(x_c1, y_c1)):
            self.outer_curve_output.insertItem(i, str(p))
        
        for i, p in enumerate(zip(x_c2, y_c2)):
            self.inner_curve_output.insertItem(i, str(p))

        for i, p in enumerate(zip(x_L1, y_L1)):
            self.outer_line_output.insertItem(i, str(p))

        for i, p in enumerate(zip(x_L2, y_L2)):
            self.inner_line_output.insertItem(i, str(p))

        self.graphicsView.plot(x_c1, y_c1, pen=None, symbol="o")
        self.graphicsView.plot(x_c2, y_c2, pen=None, symbol="o")
        self.graphicsView.plot(x_L1,y_L1, pen=None, symbol="o")
        self.graphicsView.plot(x_L2, y_L2, pen=None, symbol="o")
        
        #return df_OC, df_IC, df_OL, df_IL
        


    def refresh_all(self):
        self.outer_curve_output.clear()
        self.inner_curve_output.clear()
        self.outer_line_output.clear()
        self.inner_line_output.clear()

        self.graphicsView.clear()

    def save_as_excel(self):
        filename = QFileDialog.getExistingDirectory()
        
        writer = pd.ExcelWriter(os.path.join(filename,"POINTS.xlsx"))

        
        self.df_OC.to_excel(writer, sheet_name="Outer_Curve",index=False)
        self.df_IC.to_excel(writer, sheet_name="Inner_Curve_Reinforcement",index=False)
        self.df_OL.to_excel(writer, sheet_name="Outer_Line",index=False)
        self.df_IL.to_excel(writer, sheet_name="Inner_Line_Reinforcement",index=False)
    
        writer.save()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
